### ISSUE TITLE
Thanks For code

### ISSUE THREAD

**Issue by durgeshsamariya** [dipanjanS/MyShinyApps#1]

**Comment by dipanjanS** [comment]
Most probably an issue with getting the data from twitter. Either authentication issue or twitteR auth mechanism has changed. Try seeing if you can fetch tweets first.

**Comment by dhruvshahh** [comment]
I am getting the same error. I think it is an issue with ggplot or withProgress() function. Could you please help me out. :)

http://stackoverflow.com/questions/31793520/shiny-app-for-twitter-not-functioning-need-help-debugging?answertab=oldest#tab-top
